- name: Add sudoers files for users
  template:
    src: "{{ sudoers_template_file }}"
    dest: /etc/sudoers
    owner: root
    group: root
    mode: 0440
  notify: restart_sshd

- name: Add custom .bashrc for new user
  template: 
    src: "{{ bashrc_template_file }}"
    dest: '/home/{{ target_user }}/.bashrc'
    owner: "{{ target_user }}"
    group: "{{ target_user }}"
    mode: 0644

- name: Add SSH Public Key for new user
  authorized_key:
    user: "{{ target_user }}"
    key: "{{ local_pub_key }}"