---
- hosts: all
  become: true
  tasks:
    - name: Create your admin user with a home directory and default shell
      ansible.builtin.user:
        name: "{{ target_user }}"
        groups: sudo
        create_home: true
        shell: /bin/bash
        append: yes
        state: present