---
- hosts: all
  become: true
  remote_user: root
  tasks:
    - name: Remove your user's group from target node
      ansible.builtin.group:
        name: jonathan
        state: absent
    
    - name: Remove your User from target node
      ansible.builtin.user:
        name: jonathan
        state: absent
        remove: yes