---
- hosts: all
  become: true
  remote_user: root
  tasks:  
    - name: Remove your User from target node
      ansible.builtin.user:
        name: "{{ target_user }}"
        state: absent
        remove: yes